# Generated by Django 3.2.7 on 2021-12-01 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('foto_projeto', models.FileField(null=True, upload_to='media/')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('cep', models.IntegerField()),
                ('foto_perfil', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEsperada', models.IntegerField(null=True, verbose_name='Horas Esperadas')),
                ('horaExecutada', models.IntegerField(null=True, verbose_name='Horas Executadas')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('descricao', models.CharField(max_length=250, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('dataAtualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Última data de atualização')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('arquivo', models.FileField(null=True, upload_to='media/')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
        ),
    ]
