# Generated by Django 3.2.7 on 2021-12-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20211201_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='dataCriacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='foto_projeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='nome',
        ),
    ]
