# Generated by Django 3.2.7 on 2021-12-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_auto_20211201_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='foto_projeto',
            field=models.FileField(upload_to='media/'),
        ),
    ]
