# Generated by Django 3.2.7 on 2021-12-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_alter_projeto_foto_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='foto_projeto',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
