# Generated by Django 3.2.7 on 2021-12-02 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_remove_projeto_foto_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foto_projeto',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
