# Generated by Django 3.2.7 on 2021-12-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0016_requisitos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitos',
            name='usuario',
        ),
    ]
