# Generated by Django 3.2.7 on 2021-12-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0019_requisitos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitos',
            name='usuario',
        ),
    ]
