# Generated by Django 3.2.7 on 2021-12-06 20:03

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0021_auto_20211206_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos',
            name='projeto',
            field=models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
    ]
