# Generated by Django 3.2.7 on 2021-12-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0027_alter_requisitos_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitos',
            name='projeto',
        ),
    ]
