# Generated by Django 3.2.7 on 2021-12-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0028_remove_requisitos_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitos',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
            preserve_default=False,
        ),
    ]
