# Generated by Django 3.2.7 on 2021-11-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0004_auto_20211111_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='descricao',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='nome',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
