# Generated by Django 3.2.7 on 2021-12-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0005_auto_20211111_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ferramentas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_site.ferramenta'),
        ),
    ]
