# Generated by Django 3.2.7 on 2021-12-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0009_auto_20211201_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('descricao', models.CharField(max_length=250, null=True)),
                ('foto_ferramenta', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
