# Generated by Django 3.2.7 on 2021-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0010_ferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ferramentas',
            field=models.ManyToManyField(to='dados_site.Ferramenta'),
        ),
    ]
