# Generated by Django 3.2.7 on 2021-12-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0011_projeto_ferramentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True)),
                ('arquivo', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaEsperada', models.IntegerField(null=True, verbose_name='Horas Esperadas')),
                ('horaExecutada', models.IntegerField(null=True, verbose_name='Horas Executadas')),
            ],
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='foto_ferramenta',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='nome',
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='requisitos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_site.requisitos'),
        ),
        migrations.AddField(
            model_name='requisitos',
            name='dataAtualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última data de atualização'),
        ),
        migrations.AddField(
            model_name='requisitos',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='documentacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_site.documentacao'),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='tempo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_site.tempo'),
        ),
    ]
