# Generated by Django 3.2.7 on 2021-12-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0012_auto_20211201_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='ferramentas',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ferramentas',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dados_site.ferramenta'),
        ),
    ]
