# Generated by Django 3.2.8 on 2021-10-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=250)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('foto_projeto', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('cep', models.IntegerField()),
                ('foto_perfil', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
