# Generated by Django 3.2.8 on 2021-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_site', '0002_ferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='descricao',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
